### ISSUE TITLE
Angular 13 error

### ISSUE THREAD

**Issue by PaolaRuby** [cornflourblue/angular-10-jwt-refresh-tokens#17]
After upgrade rxjs 6 to 7
```
Error: src/app/_helpers/app.initializer.ts:8:18 - 
error TS2345: Argument of type '(value: unknown) => void' is not assignable to parameter of type 'TeardownLogic'.
  Type '(value: unknown) => void' is not assignable to type '() => void'.

8             .add(resolve);
                   ~~~~~~~
```
Somebody know how to fix it?
Is there angular 13 version of this example?

**Comment by hainv** [comment]
I have same error. @cornflourblue Can you help me?

**Comment by fabiomartino** [comment]
Have you try this?

```
// app.initializer.ts
import { AuthenticationService } from '@app/_services';

export function appInitializer(authenticationService: AuthenticationService) {
    // return () => new Promise(resolve => { // <-- Previus version
    return () => new Promise((resolve: any) => { // <-- Not the best solution but put a type of any
        // attempt to refresh token on app start up to auto authenticate
        authenticationService.refreshToken()
            .subscribe()
            .add(resolve);
    });
}
```

**Comment by silktrader** [comment]
Pass a lambda:

```javascript
export function appInitializer(authenticationService: AuthService) {
  return () =>
    new Promise((resolve) => {
      // attempt to refresh token on app start up to auto authenticate
      authenticationService
        .refreshToken()
        .subscribe()
        .add(() => resolve);
    });
}
```
